-- CASE OS legacy module — tenant demand, sales pipeline, partner portal and private sales commissions.
-- Safe to run multiple times.

CREATE TABLE IF NOT EXISTS `brand_requests` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `brand_name` VARCHAR(190) NOT NULL,
  `country` VARCHAR(120) NULL,
  `city` VARCHAR(120) NULL,
  `category` VARCHAR(120) NULL,
  `area_min` DECIMAL(12,2) NULL,
  `area_max` DECIMAL(12,2) NULL,
  `budget_max` DECIMAL(12,2) NULL,
  `preferences` TEXT NULL,
  `stage` VARCHAR(40) NOT NULL DEFAULT 'new',
  `source` VARCHAR(80) NULL,
  `broker` VARCHAR(190) NULL,
  `next_action` VARCHAR(255) NULL,
  `due_date` DATE NULL,
  `potential_fee` DECIMAL(14,2) NULL DEFAULT 0,
  `visibility` VARCHAR(40) NOT NULL DEFAULT 'internal',
  `partner_id` BIGINT UNSIGNED NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_brand_requests_city` (`country`,`city`),
  KEY `idx_brand_requests_stage` (`stage`),
  KEY `idx_brand_requests_broker` (`broker`),
  KEY `idx_brand_requests_area` (`area_min`,`area_max`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sales_assets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(190) NOT NULL,
  `country` VARCHAR(120) NULL,
  `city` VARCHAR(120) NULL,
  `type` VARCHAR(120) NULL,
  `area` DECIMAL(14,2) NULL,
  `price` DECIMAL(16,2) NULL,
  `currency` VARCHAR(12) NOT NULL DEFAULT 'USD',
  `seller` VARCHAR(190) NULL,
  `stage` VARCHAR(40) NOT NULL DEFAULT 'lead',
  `broker` VARCHAR(190) NULL,
  `partner` VARCHAR(190) NULL,
  `visibility` VARCHAR(40) NOT NULL DEFAULT 'internal',
  `commission_rate` DECIMAL(8,4) NULL DEFAULT 0,
  `expected_commission` DECIMAL(16,2) NULL DEFAULT 0,
  `next_action` VARCHAR(255) NULL,
  `due_date` DATE NULL,
  `notes` TEXT NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_sales_assets_city` (`country`,`city`),
  KEY `idx_sales_assets_stage` (`stage`),
  KEY `idx_sales_assets_broker` (`broker`),
  KEY `idx_sales_assets_visibility` (`visibility`),
  KEY `idx_sales_assets_price` (`price`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sales_buyers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(190) NOT NULL,
  `country` VARCHAR(120) NULL,
  `city` VARCHAR(120) NULL,
  `asset_type` VARCHAR(120) NULL,
  `area_min` DECIMAL(14,2) NULL,
  `area_max` DECIMAL(14,2) NULL,
  `budget_min` DECIMAL(16,2) NULL,
  `budget_max` DECIMAL(16,2) NULL,
  `cap_rate` VARCHAR(80) NULL,
  `contact` VARCHAR(255) NULL,
  `broker` VARCHAR(190) NULL,
  `stage` VARCHAR(40) NOT NULL DEFAULT 'active',
  `notes` TEXT NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_sales_buyers_city` (`country`,`city`),
  KEY `idx_sales_buyers_broker` (`broker`),
  KEY `idx_sales_buyers_budget` (`budget_min`,`budget_max`),
  KEY `idx_sales_buyers_area` (`area_min`,`area_max`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `case_partners` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(190) NOT NULL,
  `type` VARCHAR(80) NULL,
  `country` VARCHAR(120) NULL,
  `city` VARCHAR(120) NULL,
  `email` VARCHAR(190) NULL,
  `phone` VARCHAR(80) NULL,
  `access` VARCHAR(80) NOT NULL DEFAULT 'readonly',
  `scope` VARCHAR(120) NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'pending',
  `owner` VARCHAR(190) NULL,
  `notes` TEXT NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_case_partners_status` (`status`),
  KEY `idx_case_partners_owner` (`owner`),
  KEY `idx_case_partners_city` (`country`,`city`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `partner_referrals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `partner_id` BIGINT UNSIGNED NULL,
  `partner_name` VARCHAR(190) NULL,
  `kind` VARCHAR(60) NOT NULL DEFAULT 'brand_request',
  `name` VARCHAR(190) NOT NULL,
  `country` VARCHAR(120) NULL,
  `city` VARCHAR(120) NULL,
  `category` VARCHAR(120) NULL,
  `area_min` DECIMAL(14,2) NULL,
  `area_max` DECIMAL(14,2) NULL,
  `budget_min` DECIMAL(16,2) NULL,
  `budget_max` DECIMAL(16,2) NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'new',
  `broker` VARCHAR(190) NULL,
  `notes` TEXT NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_partner_referrals_partner` (`partner_id`),
  KEY `idx_partner_referrals_kind` (`kind`),
  KEY `idx_partner_referrals_broker` (`broker`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sales_commission_ledger` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sales_asset_id` BIGINT UNSIGNED NULL,
  `asset_name` VARCHAR(190) NULL,
  `broker` VARCHAR(190) NULL,
  `partner` VARCHAR(190) NULL,
  `case_commission` DECIMAL(16,2) NULL DEFAULT 0,
  `agent_bonus` DECIMAL(16,2) NULL DEFAULT 0,
  `partner_bonus` DECIMAL(16,2) NULL DEFAULT 0,
  `weighted_bonus` DECIMAL(16,2) NULL DEFAULT 0,
  `lost_bonus` DECIMAL(16,2) NULL DEFAULT 0,
  `stage` VARCHAR(40) NULL,
  `probability` DECIMAL(6,4) NULL DEFAULT 0,
  `status` VARCHAR(40) NOT NULL DEFAULT 'pipeline',
  `visibility` VARCHAR(40) NOT NULL DEFAULT 'own_private',
  `notes` TEXT NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_sales_commission_broker` (`broker`),
  KEY `idx_sales_commission_asset` (`sales_asset_id`),
  KEY `idx_sales_commission_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
