-- CASE OS legacy module — two commission engines: lease department + supplier mediation.
-- Safe to run multiple times. Parameters are in tables, not hardcoded.

CREATE TABLE IF NOT EXISTS `commission_engine_settings` (
  `setting_key` VARCHAR(80) NOT NULL,
  `setting_value` JSON NULL,
  `updated_by` VARCHAR(190) NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `commission_engine_settings` (`setting_key`,`setting_value`) VALUES
('lease_distribution', JSON_OBJECT(
  'baseMethod','manual',
  'annualPercent',8,
  'fixedAmount',0,
  'needsAshConfirmation',true,
  'curatorName','Нодир',
  'supportName','Хилола',
  'curatorSelfShare',25,
  'externalAgentShare',20,
  'internalAgentShare',15,
  'curatorShare',5,
  'supportShare',5,
  'scenario3CompanyShare',75,
  'salaryAllocationMode','period',
  'internalMonthlySalary',0,
  'offTheTop',true
)),
('supplier_distribution', JSON_OBJECT(
  'defaultCommissionRate',5,
  'defaultClientDiscount',5,
  'requireDisclosureBeforePaid',true
))
ON DUPLICATE KEY UPDATE setting_key=setting_key;

CREATE TABLE IF NOT EXISTS `lease_commission_deals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `obj_id` VARCHAR(32) NULL,
  `object_name` VARCHAR(190) NULL,
  `unit_id` BIGINT UNSIGNED NULL,
  `unit_code` VARCHAR(120) NULL,
  `tenant_name` VARCHAR(190) NOT NULL,
  `area` DECIMAL(14,2) NULL DEFAULT 0,
  `rate` DECIMAL(14,2) NULL DEFAULT 0,
  `monthly_rent` DECIMAL(16,2) NULL DEFAULT 0,
  `annual_rent` DECIMAL(16,2) NULL DEFAULT 0,
  `term_months` INT NULL DEFAULT 12,
  `signed_date` DATE NULL,
  `currency` VARCHAR(12) NOT NULL DEFAULT 'USD',
  `fx_rate` DECIMAL(14,4) NULL DEFAULT 0,
  `base_method` VARCHAR(40) NOT NULL DEFAULT 'manual',
  `annual_percent` DECIMAL(8,4) NULL DEFAULT 8,
  `fixed_amount` DECIMAL(16,2) NULL DEFAULT 0,
  `commission_base` DECIMAL(16,2) NOT NULL DEFAULT 0,
  `ash_confirmed` TINYINT(1) NOT NULL DEFAULT 0,
  `closing_type` VARCHAR(40) NOT NULL DEFAULT 'external',
  `agent_primary` VARCHAR(190) NULL,
  `agent_secondary` VARCHAR(190) NULL,
  `split_primary` DECIMAL(8,4) NULL DEFAULT 100,
  `split_secondary` DECIMAL(8,4) NULL DEFAULT 0,
  `curator_name` VARCHAR(190) NULL,
  `support_name` VARCHAR(190) NULL,
  `agent_amount` DECIMAL(16,2) NULL DEFAULT 0,
  `curator_amount` DECIMAL(16,2) NULL DEFAULT 0,
  `support_amount` DECIMAL(16,2) NULL DEFAULT 0,
  `company_amount` DECIMAL(16,2) NULL DEFAULT 0,
  `salary_allocation` DECIMAL(16,2) NULL DEFAULT 0,
  `company_net` DECIMAL(16,2) NULL DEFAULT 0,
  `stage` VARCHAR(40) NOT NULL DEFAULT 'lead',
  `probability` DECIMAL(8,4) NULL DEFAULT 0,
  `payment_status` VARCHAR(40) NOT NULL DEFAULT 'pending',
  `reversal_of` BIGINT UNSIGNED NULL,
  `notes` TEXT NULL,
  `audit_json` JSON NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_lease_comm_deals_tenant` (`tenant_name`),
  KEY `idx_lease_comm_deals_agent` (`agent_primary`),
  KEY `idx_lease_comm_deals_curator` (`curator_name`),
  KEY `idx_lease_comm_deals_status` (`payment_status`),
  KEY `idx_lease_comm_deals_stage` (`stage`),
  KEY `idx_lease_comm_deals_signed` (`signed_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `lease_commission_ledger` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lease_deal_id` BIGINT UNSIGNED NULL,
  `participant_name` VARCHAR(190) NOT NULL,
  `participant_role` VARCHAR(60) NOT NULL,
  `role_key` VARCHAR(40) NULL,
  `amount` DECIMAL(16,2) NOT NULL DEFAULT 0,
  `currency` VARCHAR(12) NOT NULL DEFAULT 'USD',
  `fx_rate` DECIMAL(14,4) NULL DEFAULT 0,
  `amount_usd` DECIMAL(16,2) NULL DEFAULT 0,
  `amount_uzs` DECIMAL(18,2) NULL DEFAULT 0,
  `share_percent` DECIMAL(8,4) NULL DEFAULT 0,
  `stage` VARCHAR(40) NULL,
  `probability` DECIMAL(8,4) NULL DEFAULT 0,
  `status` VARCHAR(40) NOT NULL DEFAULT 'pending',
  `visibility_owner` VARCHAR(190) NULL,
  `period_month` VARCHAR(7) NULL,
  `notes` TEXT NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_lease_ledger_deal` (`lease_deal_id`),
  KEY `idx_lease_ledger_participant` (`participant_name`),
  KEY `idx_lease_ledger_owner` (`visibility_owner`),
  KEY `idx_lease_ledger_status` (`status`),
  KEY `idx_lease_ledger_period` (`period_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `supplier_categories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_ru` VARCHAR(190) NOT NULL,
  `name_uz` VARCHAR(190) NULL,
  `name_en` VARCHAR(190) NULL,
  `commission_rate` DECIMAL(8,4) NOT NULL DEFAULT 5,
  `client_discount_rate` DECIMAL(8,4) NOT NULL DEFAULT 5,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `notes` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_supplier_cat_ru` (`name_ru`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `supplier_categories` (`name_ru`,`name_uz`,`name_en`,`commission_rate`,`client_discount_rate`) VALUES
('Реклама и вывеска','Tashqi reklama va peshlavha','Outdoor advertising / signage',10,5),
('Fit-out','Fit-out','Fit-out',5,3),
('MEP / инженерия','MEP / muhandislik','MEP / engineering',5,3),
('Мебель и оборудование','Mebel va jihozlar','Furniture and equipment',4,3),
('Безопасность','Xavfsizlik','Security',5,3),
('Клининг','Klining','Cleaning',5,3),
('IT / кассовое оборудование','IT / kassa jihozlari','IT / POS equipment',4,2),
('Дизайн / проектирование','Dizayn / loyiha','Design / architecture',5,2),
('Строительные материалы','Qurilish materiallari','Construction materials',3,2),
('Логистика','Logistika','Logistics',3,2)
ON DUPLICATE KEY UPDATE commission_rate=VALUES(commission_rate), client_discount_rate=VALUES(client_discount_rate);

CREATE TABLE IF NOT EXISTS `suppliers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(190) NOT NULL,
  `category_id` BIGINT UNSIGNED NULL,
  `category_name` VARCHAR(190) NULL,
  `contact_name` VARCHAR(190) NULL,
  `phone` VARCHAR(80) NULL,
  `email` VARCHAR(190) NULL,
  `terms` TEXT NULL,
  `commission_rate` DECIMAL(8,4) NULL DEFAULT 0,
  `client_discount_rate` DECIMAL(8,4) NULL DEFAULT 0,
  `transparency_policy` TEXT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'active',
  `owner` VARCHAR(190) NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_suppliers_category` (`category_id`),
  KEY `idx_suppliers_status` (`status`),
  KEY `idx_suppliers_owner` (`owner`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `supplier_commission_deals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `supplier_id` BIGINT UNSIGNED NULL,
  `supplier_name` VARCHAR(190) NULL,
  `category_id` BIGINT UNSIGNED NULL,
  `category_name` VARCHAR(190) NULL,
  `client_name` VARCHAR(190) NOT NULL,
  `client_type` VARCHAR(60) NULL,
  `project_name` VARCHAR(190) NULL,
  `order_amount` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `currency` VARCHAR(12) NOT NULL DEFAULT 'USD',
  `fx_rate` DECIMAL(14,4) NULL DEFAULT 0,
  `commission_rate` DECIMAL(8,4) NOT NULL DEFAULT 0,
  `case_commission` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `client_discount_rate` DECIMAL(8,4) NOT NULL DEFAULT 0,
  `client_saving` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `client_disclosure` TINYINT(1) NOT NULL DEFAULT 0,
  `supplier_disclosure` TINYINT(1) NOT NULL DEFAULT 0,
  `disclosure_date` DATE NULL,
  `disclosure_by` VARCHAR(190) NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'expected',
  `payment_status` VARCHAR(40) NOT NULL DEFAULT 'expected',
  `owner` VARCHAR(190) NULL,
  `notes` TEXT NULL,
  `audit_json` JSON NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_supplier_deals_supplier` (`supplier_id`),
  KEY `idx_supplier_deals_client` (`client_name`),
  KEY `idx_supplier_deals_owner` (`owner`),
  KEY `idx_supplier_deals_status` (`status`),
  KEY `idx_supplier_deals_payment` (`payment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `supplier_commission_ledger` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `supplier_deal_id` BIGINT UNSIGNED NULL,
  `supplier_name` VARCHAR(190) NULL,
  `client_name` VARCHAR(190) NULL,
  `case_commission` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `client_saving` DECIMAL(18,2) NOT NULL DEFAULT 0,
  `currency` VARCHAR(12) NOT NULL DEFAULT 'USD',
  `status` VARCHAR(40) NOT NULL DEFAULT 'expected',
  `visibility_owner` VARCHAR(190) NULL,
  `period_month` VARCHAR(7) NULL,
  `notes` TEXT NULL,
  `created_by` VARCHAR(190) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_supplier_ledger_deal` (`supplier_deal_id`),
  KEY `idx_supplier_ledger_owner` (`visibility_owner`),
  KEY `idx_supplier_ledger_status` (`status`),
  KEY `idx_supplier_ledger_period` (`period_month`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
